from django.core.management.base import BaseCommand
from core.models import Curso

class Command(BaseCommand):
    def handle(self, *args, **kwargs):
        cursos = [
          "OPERACIÓN DE MONTACARGAS",
        "CURSO PARA LA OPERACIÓN DEL MÓDULO DE PROCEDIMIENTOS DE CONTRATACIÓN EN LA PLATAFORMA COMPRAS MX",
        "REGULARIZACIÓN NORMATIVA EN MATERIA DE IMPACTO AMBIENTAL",
        "FÚTBOL SIN CORRER: FUNDAMENTOS PARA UN JUEGOLIMPIO Y SEGURO",
        "ABORDAJE DE TRASTORNOS POR CONSUMO DE SUSTANCIAS EN EL TERCER NIVEL DE ATENCIÓN CON BASE EN EL NUEVO MODELO MEXICANO",
        "DIVERSIDAD SEXUAL Y DERECHOS HUMANOS",
        "ACCIONES PARA ABORDAR RIESGOS Y OPORTUNIDADES",
        "EQUIPOS DE REFRIGERACIÓN Y AIRE ACONDICIONADO",
        "ISO 9001 : 2026 Y SUS NUEVOS REQUERIMENTOS",
        "CONTROL DE LA INFORMACIÓN DOCUMENTADA",
        "CUMPLIMIENTO DEL REQUISITO CALIBRACIÓN DE INSTRUMENTOS DE MEDICIÓN",
        "PLATICA DE INDUCCIÓN AL PERSONAL DE NUEVO INGRESO",
        "PLATICA DE SEGURIDAD E HIGIENE AL PERSONAL DE NUEVO INGRESO",
        "PLATICA DE INDUCCIÓN IMSS AL PERSONAL DE NUEVO INGRESO",
        "AUTONOMIÁ Y DERECHOS HUMANOS DE LAS MUJERES",
        "CUMPLIMIENTO DE LA LEY GENERAL DE ARCHIVOS Y NORMATIVIDAD EN MATERIA DE ARCHIVOS 2026",
        "AYUNO INTERMITENTE: CUIDADO DE LA SALUD Y EL PESO CORPORAL",
        "LA EPILEPSIA EN LA NIÑEZ ¿UNA ENFERMEDAD RARA?",
        "ATENCIÓN A TRASTORNOS MENTALES BASADA EN LA ESTRATEGIA mhGAP",
        "CURSO DE ACTUALIZACIÓN EN TERAPIA TRANSPERSONAL",
        "CURSO DE ACTUALIZACIÓN EN LA CLASIFICACIÓN INTERNACIONAL DE ENFERMEDADES 11a REVISIÓN (CIE-11)",
        "ACOSO ESCOLAR, VIOLENCIA ESCOLAR Y EN LA ESCUELA",
        "DERECHOS HUMANOS Y COMPETENCIAS SOCIOEMOCIONALES",
        "DIVERSIDAD Y DERECHOS LINGUISTICOS DE LOS PUEBLOS INDÍGENAS DE MÉXICO",
        "ENFERMEDADES DE TRABAJO",
        "PLATICA DE INDUCCION AL SGC-MLS",
        "HERRAMIENTAS BASICAS DE MICROSOFT OFFICE 2010.WORD",
        "PROBLEMAS DE CONDUCTA Y DESARROLLO EN NIÑOS Y/O ADOLECENTES? ESTRATEGIAS DE SOLUCION PARA VIVIR MEJOR",
        "TRABAJO EN EQUIPO",
        "LENGUAJE CIUDADANO",
        "AMENAZAS DIGITALES Y SEGURIDAD DE LA INFORMACION",
        "PREVENCION Y CONTROL DEL CANCER DE MAMA"
        ]

        for c in cursos:
            Curso.objects.get_or_create(nombre=c)

        print("Cursos cargados")