# cargar_cursos.py
import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from core.models import Curso

lista_cursos = [
    "ATENCIÓN SOCIOSANITARIA DE LAS PERSONAS MAYORES EN EL DOMICILIO (FORTALECIMIENTO DE LAS COMPETENCIAS EN EL PERSONAL DE ENFERMERÍA)",
    "OPERACIÓN DE MONTACARGAS",
    "CURSO PARA LA OPERACIÓN DEL MÓDULO DE PROCEDIMIENTOS DE CONTRATACIÓN EN LA PLATAFORMA COMPRAS MX",
    "REGULARIZACIÓN NORMATIVA EN MATERIA DE IMPACTO AMBIENTAL",
    "FÚTBOL SIN CORRER: FUNDAMENTOS PARA UN JUEGO LIMPIO Y SEGURO",
    "ABORDAJE DE TRASTORNOS POR CONSUMO DE SUSTANCIAS EN EL TERCER NIVEL DE ATENCIÓN CON BASE EN EL NUEVO MODELO MEXICANO",
    "DIVERSIDAD SEXUAL Y DERECHOS HUMANOS",
    "ACCIONES PARA ABORDAR RIESGOS Y OPORTUNIDADES",
    "EQUIPOS DE REFRIGERACIÓN Y AIRE ACONDICIONADO",
    "ISO 9001: 2026 Y SUS NUEVOS REQUERIMIENTOS",
    "CONTROL DE LA INFORMACIÓN DOCUMENTADA",
    "CUMPLIMIENTO DEL REQUISITO DE CALIBRACIÓN DE INSTRUMENTOS DE MEDICIÓN",
    "PLÁTICA DE INDUCCIÓN AL PERSONAL DE NUEVO INGRESO",
    "PLÁTICA DE SEGURIDAD E HIGIENE AL PERSONAL DE NUEVO INGRESO",
    "PLÁTICA DE INDUCCIÓN IMSS AL PERSONAL DE NUEVO INGRESO",
    "AUTONOMÍA Y DERECHOS HUMANOS DE LAS MUJERES",
    "CUMPLIMIENTO DE LA LEY GENERAL DE ARCHIVOS Y NORMATIVIDAD EN MATERIA DE ARCHIVOS 2026",
    "AYUNO INTERMITENTE: CUIDADO DE LA SALUD Y EL PESO CORPORAL",
    "LA EPILEPSIA EN LA NIÑEZ ¿UNA ENFERMEDAD RARA?",
    "ATENCIÓN A TRASTORNOS MENTALES BASADA EN LA ESTRATEGIA mhGAP",
    "CURSO DE ACTUALIZACIÓN EN TERAPIA TRANSPERSONAL",
    "CURSO DE ACTUALIZACIÓN EN LA CLASIFICACIÓN INTERNACIONAL DE ENFERMEDADES (CIE-11)",
    "ACOSO ESCOLAR Y VIOLENCIA EN LA ESCUELA",
    "DERECHOS HUMANOS Y COMPETENCIAS SOCIOEMOCIONALES",
    "DIVERSIDAD Y DERECHOS LINGÜÍSTICOS DE LOS PUEBLOS INDÍGENAS DE MÉXICO",
    "ENFERMEDADES DE TRABAJO",
    "PLÁTICA DE INDUCCIÓN AL SGC-MLS",
    "HERRAMIENTAS BÁSICAS DE MICROSOFT OFFICE (WORD)",
    "PROBLEMAS DE CONDUCTA Y DESARROLLO EN NIÑOS Y ADOLESCENTES: ESTRATEGIAS DE SOLUCIÓN",
    "TRABAJO EN EQUIPO",
    "LENGUAJE CIUDADANO",
    "AMENAZAS DIGITALES Y SEGURIDAD DE LA INFORMACIÓN",
    "PREVENCIÓN Y CONTROL DEL CÁNCER DE MAMA",
    "DERECHOS HUMANOS Y VIOLENCIA",
    "PERSONAS CON DISCAPACIDAD: TRANSFORMANDO BARRERAS EN OPORTUNIDADES",
    "1RA SESIÓN: PRESENTACIÓN E INTEGRACIÓN",
    "2DA SESIÓN: ES MEJOR PREVENIR",
    "3RA SESIÓN: ME CONOZCO",
    "CURSO PARA PADRES: DETECCIÓN Y PREVENCIÓN DEL CONSUMO DE SUSTANCIAS",
    "HABLEMOS DE SUSTANCIAS PSICOACTIVAS",
    "UNA AVENTURA PARA VIVIR UNA ADOLESCENCIA SEGURA",
    "SANAMENTE LIBREMENTE: JÓVENES POR LA PAZ Y CONTRA LAS ADICCIONES",
    "INTRODUCCIÓN A LA ADMINISTRACIÓN PÚBLICA FEDERAL",
    "ÉTICA E INTEGRIDAD PÚBLICA PARA UN BUEN GOBIERNO",
    "LEY DE ADQUISICIONES, ARRENDAMIENTOS Y SERVICIOS DEL SECTOR PÚBLICO",
    "INTRODUCCIÓN A LA CIBERSEGURIDAD",
    "ÉTICA, PRÁCTICA Y MÍSTICA DEL SERVICIO PÚBLICO",
    "REDES QUE CUIDAN",
    "PRIMEROS AUXILIOS PSICOLÓGICOS",
    "ENFOQUE DE DERECHOS HUMANOS EN EL SERVIDOR PÚBLICO",
    "CLIMATERIO Y MENOPAUSIA: AUTOCONOCIMIENTO EN LA DIVERSIDAD",
    "HERRAMIENTAS PARA DOCENTES PARA PREVENIR EL CONSUMO DE FENTANILO",
    "FUTSAL: ELEMENTOS BÁSICOS PARA EL JUEGO LIMPIO",
    "IMSSFÓRMATE",
    "PROTECCIÓN DE LA POBLACIÓN JOVEN ANTE NUEVAS SUSTANCIAS PSICOACTIVAS",
    "ADICCIONES Y SUS REPERCUSIONES EN EL ENTORNO LABORAL",
    "PREVENCIÓN Y DETECCIÓN DEL MALTRATO INFANTIL",
    "CURSO DE FORMACIÓN INICIAL PARA PERSONAS CUIDADORAS DE PERSONAS MAYORES",
    "ELABORACIÓN DEL CUADRO GENERAL DE CLASIFICACIÓN ARCHIVÍSTICA Y CATÁLOGO DOCUMENTAL 2026",
    "ENVEJECIMIENTO SALUDABLE",
    "CERO TOLERANCIA AL MALTRATO INFANTIL",
    "PREVENCIÓN DE LAS ADICCIONES EN EL ÁMBITO LABORAL",
    "MANEJO DE HOJAS DE CÁLCULO BÁSICO II"
]

def cargar_datos():
    print("Iniciando carga de cursos...")
    creados = 0

    for nombre in lista_cursos:
        _, creado = Curso.objects.get_or_create(nombre=nombre)
        if creado:
            creados += 1
            print(f"✔ Añadido: {nombre}")

    print(f"\n✅ Se agregaron {creados} cursos nuevos.")

if __name__ == '__main__':
    cargar_datos()

    #from core.models import Curso
#Curso.objects.all().delete()
    #