# cargar_cursos.py
import os
import django 

# Configurar el entorno de Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')  # <- Reemplaza 'tu_proyecto' por el nombre de tu carpeta principal
django.setup()

from core.models import Curso  # <- Reemplaza 'cursos' por el nombre de tu app

lista_cursos = [   
     "ATENCIÓN SOCIOSANITARIA DE LAS PERSONAS MAYORES EN EL DOMICILIO. (FORTALECIMIENTO DE LAS COMPETENCIAS EN EL PERSONAL DE ENFERMERÍA)",
    "OPERACIÓN DE MONTACARGAS",
    "CURSO PARA LA OPERACIÓN DEL MÓDULO DE PROCEDIMIENTOS DE CONTRATACIÓN EN LA PLATAFORMA COMPRAS MX",
    "REGULARIZACIÓN NORMATIVA EN MATERIA DE IMPACTO AMBIENTAL",
    "FÚTBOL SIN CORRER: FUNDAMENTOS PARA UN JUEGO LIMPIO Y SEGURO",
    "ABORDAJE DE TRASTORNOS POR CONSUMO DE SUSTANCIAS EN EL TERCER NIVEL DE ATENCIÓN CON BASE EN EL NUEVO MODELO MEXICANO",
    "DIVERSIDAD SEXUAL Y DERECHOS HUMANOS",
    "ACCIONES PARA ABORDAJE DE RIESGOS Y OPORTUNIDADES",
    "EQUIPOS DE REFRIGERACIÓN Y AIRE ACONDICIONADO",
    "ISO 9001 : 2026 Y SUS NUEVOS REQUERIMIENTOS",
    "CONTROL DE LA INFORMACIÓN DOCUMENTADA",
    "CUMPLIMIENTO DEL REQUISITO CALIBRACIÓN DE INSTRUMENTOS DE MEDICIÓN",
    "PLÁTICA DE INDUCCIÓN AL PERSONAL DE NUEVO INGRESO",
    "PLÁTICA DE INDUCCIÓN E HIGIENE AL PERSONAL DE NUEVO INGRESO",
    "PLÁTICA DE INDUCCIÓN IMSS AL PERSONAL DE NUEVO INGRESO",
    "AUTONOMÍA Y DERECHOS HUMANOS DE LAS MUJERES",
    "CUMPLIMIENTO DE LA LEY GENERAL DE ARCHIVOS Y NORMATIVIDAD EN MATERIA DE ARCHIVOS 2026",
    "AYUNO INTERMITENTE: CUIDADO DE LA SALUD Y EL PESO CORPORAL",
    "LA EPILEPSIA EN LA NIÑEZ ¿UNA ENFERMEDAD RARA?",
    "ATENCIÓN A TRASTORNOS MENTALES BASADA EN LA ESTRATEGIA mhGAP",
    "CURSO DE ACTUALIZACIÓN EN TERAPIA TRANSPERSONAL",
    "CURSO DE ACTUALIZACIÓN EN LA CLASIFICACIÓN INTERNACIONAL DE ENFERMEDADES 11a REVISIÓN (CIE-11)",
    "ACOSO ESCOLAR, VIOLENCIA ESCOLAR Y EN LA ESCUELA",
    "DERECHOS HUMANOS Y COMPETENCIAS SOCIOEMOCIONALES",
    "DIVERSIDAD Y DERECHOS LINGÜÍSTICOS DE LOS PUEBLOS INDÍGENAS DE MÉXICO",
    "ENFERMEDADES DE TRABAJO",
    "PLÁTICA DE INDUCCIÓN AL SGC-MLS",
    "HERRAMIENTAS BÁSICAS DE MICROSOFT OFFICE 2010. WORD",
    "PROBLEMAS DE CONDUCTA Y DESARROLLO EN NIÑOS Y/O ADOLESCENTES? ESTRATEGIAS DE SOLUCIÓN PARA VIVIR MEJOR",
    "TRABAJO EN EQUIPO",
    "LENGUAJE CIUDADANO",
    "AMENAZAS DIGITALES Y SEGURIDAD DE LA INFORMACIÓN",
    "PREVENCIÓN Y CONTROL DEL CÁNCER DE MAMA",
    "PLÁTICA DE SEGURIDAD E HIGIENE AL PERSONAL DE NUEVO INGRESO",
    "DERECHOS HUMANOS Y VIOLENCIA",
    "PERSONAS CON DISCAPACIDAD; TRASFORMANDO BARRERAS EN OPURTUNIDADES",
     "1RA SESION/PRESENTACION  INTEGRACION",
     "2DA.SESION/ES MEJOR PREVENIR",
     "3DA.SESION/ME CONOZCO",
     "ÉTICA,PRACTICA Y MITICA",
     "INTRODUCCIÓN A LA CIBERSEGURIDAD",
     "ÉTICA E INTEGRIDAD PUBLICA PARA UN BUEN GOBIERNO",
     "INTRODUCCIÓN A LA ADMINISTRACION PUBLICA GENERAL",
     
]

def cargar_datos():
    print("Iniciando la carga de cursos a SQLite...")
    creados = 0
    for nombre_curso in lista_cursos:
        # get_or_create evita duplicar el curso si ejecutas el script más de una vez
        curso, creado = Curso.objects.get_or_create(nombre=nombre_curso)
        if creado:
            creados += 1
            print(f"Añadido: {nombre_curso}")
    
    print(f"\n¡Proceso terminado! Se agregaron {creados} cursos nuevos a la base de datos.")

if __name__ == '__main__':
    cargar_datos()