# Generated by Django 6.0.6 on 2026-06-18 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.IntegerField(verbose_name='Consecutivo')),
                ('nombre_tipo_capacitacion', models.CharField(max_length=255, verbose_name='Nombre Tipo Capacitación')),
                ('participantes_operativos', models.PositiveIntegerField(default=0, verbose_name='Participantes Operativos')),
                ('hombres', models.PositiveIntegerField(default=0, verbose_name='Hombres')),
                ('mujeres', models.PositiveIntegerField(default=0, verbose_name='Mujeres')),
                ('fortalecimiento_desempenio', models.PositiveIntegerField(default=0, verbose_name='Fortalecimiento del Desempeño')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['consecutivo'],
            },
        ),
        migrations.CreateModel(
            name='CargaSTPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_estado', models.CharField(blank=True, max_length=10, null=True)),
                ('clave_municipio', models.CharField(blank=True, max_length=10, null=True)),
                ('clave_ocupacion', models.CharField(blank=True, max_length=20, null=True)),
                ('clave_niv_estudio', models.CharField(blank=True, max_length=10, null=True)),
                ('clave_doc_probatorio', models.CharField(blank=True, max_length=10, null=True)),
                ('clave_institucion', models.CharField(blank=True, max_length=50, null=True)),
                ('clave_curso', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_curso', models.CharField(blank=True, max_length=200, null=True)),
                ('clave_area_tematica', models.CharField(blank=True, max_length=20, null=True)),
                ('duracion', models.CharField(blank=True, max_length=10, null=True)),
                ('fec_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('fec_termino', models.CharField(blank=True, max_length=20, null=True)),
                ('clave_tip_agent', models.CharField(blank=True, max_length=10, null=True)),
                ('rfc_agente_stps', models.CharField(blank=True, max_length=15, null=True)),
                ('clave_modalidad', models.CharField(blank=True, max_length=10, null=True)),
                ('clave_capacitacion', models.CharField(blank=True, max_length=10, null=True)),
                ('clave_establec', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CursoExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(verbose_name='Número')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Curso')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('constancia', models.IntegerField(default=0, verbose_name='Constancias')),
                ('operativo', models.IntegerField(default=0, verbose_name='Operativo')),
                ('promotores', models.IntegerField(default=0, verbose_name='Promotores')),
                ('administrativo', models.IntegerField(default=0, verbose_name='Administrativo')),
                ('confianza', models.IntegerField(default=0, verbose_name='Confianza')),
                ('hombres', models.IntegerField(default=0, verbose_name='Hombres')),
                ('mujeres', models.IntegerField(default=0, verbose_name='Mujeres')),
                ('mes', models.CharField(default='06', max_length=2, verbose_name='Mes del Registro')),
            ],
            options={
                'verbose_name': 'Curso Excel',
                'verbose_name_plural': 'Cursos Excel',
            },
        ),
        migrations.CreateModel(
            name='ProgramaReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=1, verbose_name='No.')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('importe', models.FloatField(default=0, verbose_name='Importe')),
                ('tipo_accion', models.CharField(max_length=100, verbose_name='Tipo de Acción')),
                ('modalidad', models.CharField(max_length=100, verbose_name='Modalidad')),
                ('fecha', models.CharField(max_length=100, verbose_name='Fecha')),
                ('instructor', models.CharField(max_length=100, verbose_name='Instructor Interno ó Externo')),
                ('constancia', models.IntegerField(verbose_name='Constancia')),
                ('operativo', models.IntegerField(default=0, verbose_name='Operativo Sindicalizado')),
                ('promotores', models.IntegerField(default=0, verbose_name='Promotores Sociales')),
                ('administrativo', models.IntegerField(default=0, verbose_name='Administrativo Sindicalizado')),
                ('confianza', models.IntegerField(default=0, verbose_name='Confianza')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCaptura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=1, verbose_name='No.')),
                ('centro_costos', models.CharField(max_length=100, verbose_name='Centro de Costos')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto')),
                ('nomina', models.CharField(max_length=50, verbose_name='Nómina')),
                ('nombre_trabajador', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('curp', models.CharField(max_length=18, verbose_name='CURP')),
                ('induccion', models.BooleanField(default=False, verbose_name='Inducción')),
                ('columna_ind1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Columna1 (Inducción)')),
                ('columna_ind2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Columna2 (Inducción)')),
                ('capacitacion', models.BooleanField(default=False, verbose_name='Capacitación')),
                ('columna_cap1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Columna1 (Capacitación)')),
                ('columna_cap2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Columna2 (Capacitación)')),
                ('modalidad_curso', models.CharField(default='', max_length=100, verbose_name='Modalidad del Curso')),
                ('fecha_inicio', models.DateField(verbose_name='FI')),
                ('fecha_termino', models.DateField(verbose_name='FT')),
                ('duracion', models.IntegerField(verbose_name='D')),
                ('genero', models.CharField(max_length=10, verbose_name='Género')),
                ('costo', models.CharField(max_length=20, verbose_name='Costo')),
                ('total_horas', models.IntegerField(verbose_name='Total de Horas')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso', verbose_name='Nombre del Curso')),
            ],
        ),
    ]
