# Generated by Django 6.0.6 on 2026-07-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_areatematica'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatálogoOcupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True, verbose_name='Clave Ocupación')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Ocupación')),
            ],
            options={
                'verbose_name': 'Catálogo de Ocupación',
                'verbose_name_plural': 'Catálogo de Ocupaciones',
            },
        ),
    ]
