# Generated by Django 6.0.6 on 2026-07-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_catálogoocupacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatálogoOcupacion',
            new_name='CatalogoOcupacion',
        ),
    ]
