# Generated by Django 6.0.6 on 2026-07-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_catálogoocupacion_catalogoocupacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogoocupacion',
            options={},
        ),
        migrations.AlterField(
            model_name='catalogoocupacion',
            name='clave',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='catalogoocupacion',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
