# Generated by Django 6.0.6 on 2026-07-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_catalogoocupacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoocupacion',
            name='clave',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='catalogoocupacion',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
