# Generated by Django 6.0.6 on 2026-07-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_catalogoocupacion_clave_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogoocupacion',
            options={'ordering': ['clave'], 'verbose_name': 'Ocupación (Catálogo STPS)', 'verbose_name_plural': 'Catálogo de Ocupaciones'},
        ),
        migrations.AlterField(
            model_name='catalogoocupacion',
            name='clave',
            field=models.CharField(max_length=20, unique=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='catalogoocupacion',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción Completa'),
        ),
    ]
