# Generated by Django 6.0.6 on 2026-07-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_catalogoocupacion_options_and_more'),
    ]

    operations = [
    ]
