# Generated by Django 6.0.5 on 2026-07-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20260723_1606'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catalogoocupacion',
            table='catalogoocupacion',
        ),
    ]
