# Generated by Django 6.0.5 on 2026-07-29 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_catalogoocupacion_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Área')),
            ],
            options={
                'verbose_name': 'Área Laboral',
                'verbose_name_plural': 'Áreas Laborales',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SubareaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Subárea')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='core.arealaboral')),
            ],
            options={
                'verbose_name': 'Subárea Laboral',
                'verbose_name_plural': 'Subáreas Laborales',
                'ordering': ['codigo'],
            },
        ),
        migrations.DeleteModel(
            name='CatalogoOcupacion',
        ),
    ]
