# Generated by Django 6.0.5 on 2026-08-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_arealaboral_subarealaboral_delete_catalogoocupacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre / Institución')),
            ],
            options={
                'verbose_name': 'Agente / Institución',
                'verbose_name_plural': 'Catálogo de Agentes e Instituciones',
                'ordering': ['nombre'],
            },
        ),
    ]
