# Generated by Django 6.0.5 on 2026-08-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_catalogoagente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoexcel',
            name='anio',
            field=models.IntegerField(default=2026, verbose_name='Año del Registro'),
        ),
        migrations.AlterField(
            model_name='cursoexcel',
            name='mes',
            field=models.CharField(default='01', max_length=2, verbose_name='Mes del Registro'),
        ),
    ]
