# Generated by Django 6.0.5 on 2026-08-04 04:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cursoexcel_anio_alter_cursoexcel_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoexcel',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='cursoexcel',
            name='no',
            field=models.IntegerField(default=1, verbose_name='Número'),
        ),
        migrations.AlterUniqueTogether(
            name='cursoexcel',
            unique_together={('nombre', 'mes', 'anio')},
        ),
    ]
