# Generated by Django 6.0.6 on 2026-08-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cursoexcel_fecha_registro_alter_cursoexcel_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programareal',
            name='constancia',
            field=models.IntegerField(default=0, verbose_name='Constancia'),
        ),
        migrations.AlterField(
            model_name='programareal',
            name='fecha',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='programareal',
            name='instructor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Instructor Interno ó Externo'),
        ),
        migrations.AlterField(
            model_name='programareal',
            name='modalidad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='programareal',
            name='tipo_accion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Acción'),
        ),
    ]
