# Generated by Django 6.0.6 on 2026-08-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_programareal_constancia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursoexcel',
            options={'ordering': ['fecha', 'no'], 'verbose_name': 'Curso Excel', 'verbose_name_plural': 'Cursos Excel'},
        ),
        migrations.AlterUniqueTogether(
            name='cursoexcel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cursoexcel',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del curso'),
        ),
    ]
