# Generated by Django 6.0.6 on 2026-08-10 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cursoexcel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='actualizacion',
            field=models.PositiveIntegerField(default=0, verbose_name='Actualización'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='anio',
            field=models.IntegerField(default=2026, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='certificacion',
            field=models.PositiveIntegerField(default=0, verbose_name='Certificación'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='desarrollo',
            field=models.PositiveIntegerField(default=0, verbose_name='Desarrollo'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='induccion',
            field=models.PositiveIntegerField(default=0, verbose_name='Inducción'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='modalidad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='numero_acciones',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Acciones'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='participantes_categorias_especiales',
            field=models.PositiveIntegerField(default=0, verbose_name='Categorías Especiales'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='participantes_enlace',
            field=models.PositiveIntegerField(default=0, verbose_name='Participantes Enlace'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='participantes_mandos_medios',
            field=models.PositiveIntegerField(default=0, verbose_name='Mandos Medios'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='participantes_mandos_superiores',
            field=models.PositiveIntegerField(default=0, verbose_name='Mandos Superiores'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='periodo',
            field=models.CharField(default='3', max_length=20, verbose_name='Periodo (trimestre)'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='sensibilizacion',
            field=models.PositiveIntegerField(default=0, verbose_name='Sensibilización'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='tipo_capacitacion',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo Capacitación'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='consecutivo',
            field=models.IntegerField(default=1, verbose_name='Consecutivo'),
        ),
    ]
