# Generated by Django 6.0.6 on 2026-08-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_capacitacion_actualizacion_capacitacion_anio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitacion',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='capacitacion',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='capacitacion',
            name='periodo',
        ),
    ]
