# Generated by Django 6.1 on 2026-08-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_capacitacion_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancaptura',
            name='area',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='centro_costos',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Centro de Costos'),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='columna_cap1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='columna_cap2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='columna_ind1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='columna_ind2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='costo',
            field=models.CharField(blank=True, default='S/COSTO', max_length=20, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='curp',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='duracion',
            field=models.IntegerField(default=0, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='FI'),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True, verbose_name='FT'),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='genero',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='modalidad_curso',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Modalidad del Curso'),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='nomina',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nómina'),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='puesto',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='plancaptura',
            name='total_horas',
            field=models.IntegerField(default=0, verbose_name='Total de Horas'),
        ),
    ]
